### ISSUE TITLE
Possible Fix For UTF-16 Issue

### ISSUE THREAD

**Issue by charlescao460** [BMW-InnovationLab/BMW-Labeltool-Lite#9]
Hi, 

Thank you for bring us this wonderful project! You really made image-marking more efficient especially under the coronavirus new norm.

However, when I was deploying this in my environment, the UTF-16 issue did hurt me. And I found a possible fix here:
https://github.com/BMW-InnovationLab/BMW-Labeltool-Lite/blob/a5c15715eca2b0fe51b853c0543888dd78c1a889/RCV-LT-Lite-BE/Rcv.LabelTool.Logic/Utilities/EncodingUtil.cs#L18

According to MSDN: https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.unicode?view=netcore-2.1
`System.Text.Encoding.Unicode` always mean UTF-16 LE. So I think it's possible to change it to UTF-8. And UTF-8 is the default encoding for our containers) 

I don't know if this change is needed, since this tool is kind of company's internal tool. But if you think it's okay to change it, I can create a PR and do you a favor:) 
(A PR that will change `System.Text.Encoding.Unicode` to `System.Text.Encoding.UTF8`, and all related json files to UTF-8)

**Comment by roy6324** [comment]
Hello @charlescao460 ,

The debate of using Utf-8 or Utf-16 encoding in our (programmers) applications is a long lasting one. As both have their advantages and disadvantages, but I wouldn't call using neither one of them an issue.

To sum this up, the main differences between UTF-16 and UTF-8 is:
1- Their minimum bytes length used to encode : UTF-8 uses one byte minimum however UTF-16 uses two.
2- UTF-8 encodes each character between one to four bytes , however UTF-16 encodes each character in either two OR four bytes.

East Asian languages typically require less storage in UTF-16 (2 bytes are enough for 99% of East-Asian language characters) than UTF-8 (typically 3 bytes are required). Of course, for Western lanagues, UTF-8 is usually smaller (1 byte instead of 2). But let's omit the size differences since our average JSON file is 700 bytes ( nothing to what computers are able to handle nowadays). For performance: UTF-8 is much harder to decode than UTF-16. In UTF-16 characters are either a Basic Multilingual Plane character (2 bytes) or a Surrogate Pair (4 bytes). UTF-8 characters can be anywhere between 1 and 4 bytes.

A string in C# is  UTF-16 (our application is programmed using C#). UTF-16 is used internally by systems such as Microsoft Windows, the Java programming language and JavaScript/ECMAScript. It is also often used for plain text and for word-processing data files on MS Windows. System.Text.Encoding.Unicode always means UTF-16 LE. However, As of May 2019, Windows enabled us to force a process to use UTF-8 as the process code page which helps the compatibility with other OS (Windows Version 1903). I hope soon enough we'll see the world agreeing on one Unicode type. And of course, if most of our users are more comfortable with UTF-8 , we might change it in the future :)

We'd like to know more about how did the UTF-16 situation "hurt" you ?

**Comment by charlescao460** [comment]
Hi @roy6324,

Thank you for your detailed response and information. I do understand the reason you choose UTF-16 as the default encoding. And I agree that at some level UTF-16 makes programmer's life easier. 

At the first time when I was trying to deploy this on my server, I missed the UTF-16 part in README. So I created a json file using vim, which is default in UTF-8. Then I tried to run container, the error message when opening a UTF-8 json file is very misleading.  It took me a few hours to address this issue. And that's why I said it "hurt". 

Of course, as a user I am responsible to read through README. I am totally fine with the current decision. 

Thanks!

**Comment by roy6324** [comment]
You're welcome @charlescao460 ! 

We try to provide our users with the best and most simple applications in order to make the deep learning world as easy as possible. So of course, we will take your experience into consideration.

I will close this issue.
